[Add profile] -> [Adeboye Folaranmi]
CommunityPro/Practice-Contribution pull request #63
Opened 2022-01-08 15:00 UTC by Boye95

If you're adding your profile, the title of this PR should be: `[Add profile] -> [Your Name]`

## Add Adeboye Folaranmi

2022-01-08 21:46 UTC, Mannuel25 requested changes
Hello @Boye95 , thanks for contributing. However, some changes have been made since your last edit, could you pull the changes made to avoid conflicts, then add your own profile.

In addition, do ensure you add your profile to the end of column 25. The final changes should look like this: 

```
<!-- Start of column-26 -->
<td align="center">
  <a href="https://github.com/Boye95">
    <img
      src="https://avatars.githubusercontent.com/u/74235313?v=4"
      width="100px"
    />
    <br />
    <sub>Adeboye Folaranmi</sub>
  </a>
</td>
<!-- End of column-26 -->
```
If you've any issue doing that, kindly let me know.

2022-01-14 21:58 UTC, Boye95 commented
How do I go about this ? I already tried git pull and my local files haven't been updated yet.

2022-01-14 22:43 UTC, Evavic44 commented
Hey, @Boye95 try these steps to update your fork. If you have any questions or face errors, do send me a message back. 

First, do a git fetch to get the latest changes.
```
git fetch upstream
```
Next, merge the changes with your new branch.
```
git merge upstream/main
```
If you have any conflicts after merging the changes, fix the conflict and push back to your name branch.

```
git push origin add-Boye
```

2022-01-15 12:18 UTC, Boye95 commented
I followed the steps you outlined above and it seems something's is still wrong.

2022-01-15 12:21 UTC, Evavic44 commented
> I followed the steps you outlined above and it seems something's is still wrong.

You didn't fix the conflicts that's the reason. Don't worry, I'll fix and merge it.

2022-01-15 12:28 UTC, Boye95 commented
Thanks. I'd love to learn how to do it too.

2022-01-15 13:40 UTC, Evavic44 commented
> Thanks. I'd love to learn how to do it too.

Okay, lemme allow you to do it. 
Git conflicts usually occur when multiple people are making different commits to the same line. 
For example:

2022-01-15 13:56 UTC, Evavic44 commented
Do you want me to fix it? or you want to give it a try? 😁 @Boye95

2022-01-16 13:03 UTC, Boye95 commented
Thanks for the explanation but it seems the conflict has been resolved ?

2022-01-16 13:50 UTC, Evavic44 commented on Contributors.md
> +<<<<<<< HEAD
Delete both merge branch line of text

```
<<<<<<< HEAD 
```

2022-01-16 15:15 UTC, Evavic44 requested changes
@Boye95 There are currently 27 profiles in the contributors list, kindly add yours

2022-01-17 13:02 UTC, Boye95 commented on Contributors.md
> +<!-- Start of column-26 -->
I'm already number 25 on the list

2022-03-13 14:49 UTC, Evavic44 commented
This issue has been marked as stale because of no activity.

2022-03-13 14:49 UTC, closed without merging