[Add profile] -> [Add Eunit]
CommunityPro/Practice-Contribution pull request #79
Opened 2022-03-15 05:10 UTC by Eunit99

If you're adding your profile, the title of this PR should be: `[Add profile] -> [Your Name]`

## Add Eunit 

  

### What does this PR do?:

Add feature(s) 

### Issue No:

2022-03-16 01:27 UTC, Evavic44 requested changes

2022-03-16 01:27 UTC, Evavic44 commented on Contributors.md
> +<!-- Start of column-35 -->
Hey @Eunit99 can you please remove the duplicate profile you added? 

```html
<!-- Start of column-35 -->
<td align="center">
  <a href="https://github.com/AvidCoder101">
    <img
      src="https://avatars.githubusercontent.com/u/70807684?v=4"
      width="100px"
    />
    <br />
    <sub>Avid Coder</sub>
  </a>
</td>
<!-- End of column-35 -->
```

This is what your pull request looks like. Avicoder's profile is already at number 35 so delete the one you added after 36 and push again so I can merge this. 
![duplicate](https://user-images.githubusercontent.com/62628408/158498306-d881e78a-4a3c-40d4-a390-099939456f32.jpg)

If you have any questions, feel free to ask. 🙂

2022-05-10 23:23 UTC, Evavic44 commented
Closing this issue due to prolonged inactivity. If you want to add your profile, feel free to open a new issue.

2022-05-10 23:23 UTC, closed without merging

2022-05-11 09:58 UTC, Eunit99 commented
This PR should fix it: #84